### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by leo300** [toriihq/hapi-saml2#22]
There are few issues in this  /hapi-saml2/lib/controller/handlers/logout.js
1. Unable to logout because of user object invalid.

```
const user = {
     nameIdFormat,
     nameId
    }
```

It should be like this

```
const user = {
      nameIDFormat: nameIdFormat,
      nameID: nameId
    }

```

2. Also calling` await logout()` method, but in `logout: async (request) => {} ` request object return undefined.
3. CORS not defined of any routes,  (ex: login and logout) _Access to fetch at has been blocked_ when it calls ` return h.redirect(logoutUrl)`

**Comment by berzniz** [comment]
Thanks for reporting. Happy to accept PRs that includes unit tests
