### ISSUE TITLE
Support access to assertion profile from the login hook

### ISSUE THREAD

**Issue by jonathansamines** [toriihq/hapi-saml2#4]
#### Problem

Hi, I have recently implemented this library and worked great so far. I found a small issue though. Our implementation requires us to access additional attributes from the assertion profile besides `nameID`.

I looked into the implementation and found it is already there:

https://github.com/toriihq/hapi-saml2/blob/93e0987e2d4a1a1e6419298efdffafc90de4bf1b/lib/controller/handlers/callback.js#L19-L20

Just not available from the login hook:

https://github.com/toriihq/hapi-saml2/blob/93e0987e2d4a1a1e6419298efdffafc90de4bf1b/lib/controller/handlers/callback.js#L36

#### Proposal
I have the following interface change in mind to keep it backwards compatible

```js
server.register({
  plugin: HapiSaml2,
  options: {
    login(request, userIdentifier, profile) {},
  },
});
```

Would you accept a pull request to add support for it? Please let me know what you think.

**Comment by berzniz** [comment]
Hi @jonathansamines 

Yes, I would accept such a pull request, seems like something needed

**Comment by jonathansamines** [comment]
Hi @berzniz I also verified this on my end and the new feature worked as expected.  Thanks!
